import type { NextPage } from "next";
import Head from "next/head";
import { SubmitHandler, useForm } from "react-hook-form";

type Inputs = {
  firstName: string;
  lastName: string;
  email: string;
  pesel: string;
  zipCode: string;
  city: string;
  phone: string;
};

const Add: NextPage = () => {
  const { register, handleSubmit } = useForm<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => console.log(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Add new employee</h1>
      <form onSubmit={handleSubmit(onSubmit)}>
        <input type="text" {...register("firstName")} placeholder="first name" />
        <input type="text" {...register("lastName")} placeholder="last name" />
        <input type="email" {...register("email")} placeholder="email" />
        <input type="text" {...register("pesel")} placeholder="pesel number" />
        <input type="text" {...register("zipCode")} placeholder="ZIP code" />
        <input type="text" {...register("city")} placeholder="city" />
        <input type="text" {...register("phone")} placeholder="phone number" />
        <button type="submit">Add</button>
      </form>
    </>
  );
};

export default Add;
