import type { NextPage } from "next";
import Head from "next/head";

import { EmployeeTableContainer } from "../features/employee-table";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Employees List</h1>
      <EmployeeTableContainer />
    </>
  );
};

export default Home;
