import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useMemo, useState } from "react";
import { useTable } from "react-table";

import type { EmployeeType } from "../@types";
import { getEmployees } from "../services";

const Home: NextPage = () => {
  const [employees, setEmployees] = useState([] as EmployeeType[]);

  useEffect(() => {
    const getData = async () => {
      const data = await getEmployees();
      console.log(data);
      setEmployees(data);
    };
    getData();
  }, []);

  console.log(employees);

  const data = useMemo(() => employees, [employees]);

  const columns = useMemo(
    () => [
      { Header: "First Name", accessor: "firstName" },
      { Header: "Last Name", accessor: "lastName" },
      { Header: "Email", accessor: "email" },
      { Header: "Pesel", accessor: "pesel" },
      { Header: "Zip Code", accessor: "zipCode" },
      { Header: "City", accessor: "city" },
      { Header: "Phone Number", accessor: "phone" },
    ],
    [],
  );

  const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = useTable({
    columns: columns as any, //TODO fix ts error
    data: data,
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Employees List</h1>

      <table {...getTableProps()}>
        <thead>
          {headerGroups.map((headerGroup, index) => (
            <tr {...headerGroup.getHeaderGroupProps()} key={index}>
              {headerGroup.headers.map((column, index) => (
                <th {...column.getHeaderProps()} key={index}>
                  {column.render("Header")}
                </th>
              ))}
            </tr>
          ))}
        </thead>
        <tbody {...getTableBodyProps()}>
          {rows.map((row, index) => {
            prepareRow(row);
            return (
              <tr {...row.getRowProps()} key={index}>
                {row.cells.map((cell, index) => {
                  return (
                    <td {...cell.getCellProps()} key={index}>
                      {cell.render("Cell")}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
    </>
  );
};

export default Home;
